services:
    mariadb:
        build: ./requirements/mariadb
        image: mariadb:1.0
        container_name: mariadb
        restart: always
        healthcheck:
            test: ["CMD", "mariadb", "-h", "${MYSQL_HOST}", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "-e", "SELECT 1;"]
            interval: 5s
            timeout: 60s
            retries: 12
        env_file:
            - .env
        volumes:
            - mariadb_vol:/var/lib/mysql
        expose:
            - "3306"
        networks:
            - hiver
    wordpress:
        build: ./requirements/wordpress
        image: wordpress:1.0
        container_name: wordpress
        restart: always
        healthcheck:
            test: ["CMD", "sh", "-c", "netstat -tuln | grep -q ':9000' || exit 1"]
            interval: 5s
            timeout: 60s
            retries: 12
        depends_on:
            mariadb:
                condition: service_healthy
        env_file:
            - .env
        volumes:
            - wp_vol:/var/www/wordpress
        expose:
            - "9000"
        networks:
            - hiver
    nginx:
        build: ./requirements/nginx
        image: nginx:1.0
        container_name: nginx
        restart: always
        depends_on:
            wordpress:
                condition: service_healthy
        env_file:
            - .env
        volumes:
            - wp_vol:/var/www/wordpress
        ports:
            - "443:443"
        networks:
            - hiver

volumes:
    mariadb_vol:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/mariadb
    wp_vol:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/wp

networks:
    hiver:
        driver: bridge
